// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'asdfsdf': string;
  'class': string;
  'suck-class': string;
}
export const cssExports: CssExports;
export default cssExports;
